;(define (problem pb1)
;  (:domain blocksworld)
;  (:objects a b)
;  (:init (onTable a) (onTable b) (clear a) (clear b) (equal a a) (equal b b))
;  (:goal (on a b)))
  
 (define (problem pb1)
  (:domain blocksworld)
  (:objects franka sugarBox spamBox)
  (:init (onStovetopBurner sugarBox) (onCountertop spamBox) (clear a) (clear b) (equal a a) (equal b b))
  (:goal (and (onCounterTop sugarBox) (inDrawer spamBox))))
